import React from 'react';
import { Modal, View, Text, Pressable, ScrollView, StyleSheet } from 'react-native';

type TermsAndConditionsModalProps = {
  modalVisible: boolean;
  setModalVisible: (visible: boolean) => void;
};

const TermsAndConditionsModal: React.FC<TermsAndConditionsModalProps> = ({ modalVisible, setModalVisible, setTermsAccepted }) => {
  return (
    <Modal
      visible={modalVisible}
      animationType="slide"
      transparent={true}
      onRequestClose={() => setModalVisible(false)}
    >
      <View style={styles.modalOverlay}>
        <View style={styles.modalContent}>
          <Text style={styles.modalTitle}>Terms & Conditions</Text>
          <ScrollView style={styles.modalScroll}>
            <Text style={styles.modalBody}>
              **TERMS AND CONDITIONS FOR DOCTORS**  
              **VYDHYO HEALTH CARE PRIVATE LIMITED**  
              **Effective Date: __/__/____**  

              **1. INTRODUCTION AND ACCEPTANCE OF TERMS**  
              These Terms and Conditions ("Terms") constitute a legally binding agreement ("Agreement") between Vydhyo Health Care Private Limited, a company incorporated under the Companies Act, 2013 (hereinafter referred to as "Vydhyo", "VHPL", "we", "us", or "our"), and a Registered Medical Practitioner (hereinafter referred to as "you", "your", or "Doctor"), who registers and avails services through the Vydhyo mobile application and/or the website at [https://www.vydhyo.com/consult] (collectively referred to as the "Platform").  
              By accessing, using, registering, or otherwise availing services as a Practitioner on the Platform, you acknowledge that you have read, understood, and agree to be bound by the terms of this Agreement, including the Privacy Policy available on the website and all applicable laws, regulations, and professional standards.  
              Please read these Terms carefully before using the Platform or accessing any material or information therein for providing services through [https://www.vydhyo.com/consult].  
              This Agreement is an electronic record in accordance with the provisions of the Information Technology Act, 2000 and rules framed thereunder, as applicable. It is generated by a computer system and does not require any physical or digital signatures.  
              This Agreement is published in compliance with Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011, which mandates the publication of terms of use, privacy policy, and rules and regulations for access or usage of the Platform.

              **2. INTERPRETATION**  
              2.1. The words "hereof", "hereto", "herein", and "hereunder", and words of similar import shall refer to this Agreement as a whole and not to any particular provision.  
              2.2. Words denoting the singular shall include the plural, and words denoting any gender shall include all genders.  
              2.3. Headings are included for convenience only and shall not affect the interpretation of this Agreement.  
              2.4. References to days, months, and years are to calendar days, calendar months, and calendar years as per the English calendar.  
              2.5. References to "writing" shall include printed, typed, lithographed, or electronically recorded formats and any other means of reproducing words in visible form.  
              2.6. The words "include" and "including" shall be construed without limitation.  
              2.7. "Law" shall mean and include all statutes, enactments, rules, regulations, guidelines, policies, directions, and orders issued by any competent authority within the Republic of India.  
              2.8. "Person" includes any individual, firm, partnership, corporation, company, trust, society, or any other legal or juristic entity.  
              2.9. The words "you", "your", "Doctor", or "Practitioner" shall be interpreted to include both singular and plural references, as the context requires.

              **3. DEFINITIONS**  
              The following words and terms, whenever used in this Agreement, unless repugnant to the meaning or context thereof, shall have the respective meanings set forth below.  
              3.1 “Applicable Law” shall mean all applicable national, state, or local laws, whether civil or criminal, including statutes, subordinate legislation, regulations, rules, codes of practice, GO’s, directives, ordinances, treaties, and conventions, issued or enacted by any governmental, regulatory, or statutory authority in the Republic of India, as may be amended from time to time.  
              3.2. "Vydhyo Health Care Private Limited" or "Us" or "We", shall mean and include Vydhyo Health Care Private Limited, its Offices, Officers, Directors, Partners, Owners, Administrator, independent Contractors, Employees, Agents or affiliates, and its/theirs successors and assigns.  
              3.3. "Intellectual Property Rights", which may also be referred as IPR, shall mean and include all registered and unregistered trademarks, copyright in all forms including but not limited to the contents of the Https://www.vydhyo.com/consult, images, text, illustrations, audio clips, trademarks, logos, labels, video clips, software and coding; industrial designs, patents, inventions, domain names, trade secrets, methodology, processes, features, functionality, User Information and common law rights in the aforesaid, which are associated with the Vydhyo Health Care Private Limited, Services or the System.  
              3.4. "Person" shall mean a person, and includes any individual, corporation, firm, partnership, joint venture, association, organisation, trust, state or Governmental Authority or other legal entity (in each case, whether or not having separate legal personality).  
              3.5. "Practitioner" or "Practitioners" shall mean and include medical health professional(s), and/or doctors registered and listed on the Https://www.vydhyo.com/consult.  
              3.6. "Practitioner Account Information" shall mean and include your name, email address, mobile number, password, date of birth, gender, registration number, and certain other sensitive personal information collected by the Vydhyo Health Care Private Limited or any other information required by the Vydhyo Health Care Private Limited for creation of the Practitioner Account.  
              3.7. "Practitioner Information" shall mean and include Practitioner Account Information, Practitioner generated content or any other information generated, directly or indirectly, subject to the privacy policy of the Vydhyo Health Care Private Limited, with respect to the Practitioner AccountIcon, during the process of obtaining Practitioner Services by the Practitioner, or otherwise.  
              3.8. "Practitioner Services" shall mean and include, but not limited to the following services made available by the Vydhyo Health Care Private Limited through its Https://www.vydhyo.com/consult and System:  
              3.8.1. Manage Practice Services: a) Integrated calendar for booking appointments for in clinic Consultations and b) Maintaining electronic medical records of patient visits, c) Invoicing and payment, d) SMS and email notifications to patients and User, and e) Other services which are ancillary to the area of Manage Practice.  
              3.9. "Services" shall mean and include any service(s), including User Services and Practitioner Services, provided by the Vydhyo Health Care Private Limited through its Https://www.vydhyo.com/consult and System.  
              3.10. "Https://www.vydhyo.com/consult" shall mean and include, whole or in part, the internet resource and website known as Vydhyohealth.com including but not limited to all its associated sub-domains, mobile application 'vydhyo’, any other Vydhyo Health Care Private Limited or associated data, vydhyo applications, utilities or interface.  
              3.11. "System" shall mean and include the Https://www.vydhyo.com/consult, electronic communication network including all software, all hardware, all files and images and data contained in or generated by the System associated with the Https://www.vydhyo.com/consult.  
              3.12. "Territory" shall mean and include only the territorial jurisdiction of Republic of India, to the exclusion of all other countries and territories of the world.  
              3.13. "Use" shall mean and include any use of the Https://www.vydhyo.com/consult or Services by a Person, including without limitation, Practitioner and/or the Workforce (interns, employees, servants, affiliates, representatives, agents, independent contractors employed or hired) of the Practitioner.  
              3.14. "User" and "Users" shall mean and include a registered user, unregistered user, or any Person who uses the Https://www.vydhyo.com/consult, Users, including the patient and his relative(s), representatives, agents, servants or affiliates, for whom or on whose behalf, the User is using the Https://www.vydhyo.com/consult.  
              3.15. "User Account Information" shall mean and include the name, email address, mobile number, password, date of birth, gender, city, pincode and any other information as may be required by the Vydhyo Health Care Private Limited in relation of the User Account.  
              3.16. "User Information" shall mean and include User Account Information, User generated content, Practitioner(s) generated content, medical records; information generated, directly or indirectly, subject to the privacy policy of the Vydhyo Health Care Private Limited, with respect to the User AccountIcon, during the process of obtaining User Services by the User, or otherwise.

              **4. ACCEPTANCE OF TERMS**  
              4.1. These Terms apply to all healthcare professionals (individuals or entities, including authorized associates) who list themselves on the Platform and avail the Practitioner Services.  
              4.2. If you are a member of a Practitioner’s Workforce (e.g., intern, employee, agent) authorized to use the Platform, this Agreement binds you, the Practitioner, and VHPL jointly.  
              4.3. By clicking “I Agree” or by using the Platform, you unconditionally accept these Terms in full.  
              4.4. VHPL is the owner and operator of the Platform and its associated System.  
              4.5. By using the Platform, you confirm that you are at least 18 years old, mentally competent, and legally eligible to contract.  
              4.6. If you do not understand or agree with any provision of these Terms, you should not use the Platform. Continued use implies full, unconditional acceptance.  
              4.7. Unauthorized or non-compliant use of the Platform shall be a breach of this Agreement and grants no legal rights.  
              4.8. Listing as a Practitioner or using the Platform creates a binding legal relationship with VHPL, which you affirm is entered into voluntarily and with full understanding of the consequences.

              **5. SCOPE AND APPLICABILITY**  
              5.1. These Terms are applicable to all Registered Medical Practitioners who offer medical consultation services offline, facilitated via the Platform.  
              5.2. This Agreement is governed by the laws of India, including but not limited to:  
              5.2.1 The Indian Contract Act, 1872;  
              5.2.2 The Information Technology Act, 2000;  
              5.2.3 The Telemedicine Practice Guidelines, 2020 under the Indian Medical Council Regulations;  
              5.2.4 Any other applicable regulatory or legal provisions.

              **6. PRACTITIONER REGISTRATION, OBLIGATIONS, UNDERTAKINGS AND CONSENT**  
              6.1 Authorization and Eligibility  
              6.1.1 You confirm that you are authorized to agree to these Terms and the Privacy Policy on your own behalf or on behalf of another person or legal entity.  
              6.1.2 You represent that you are not barred from receiving Practitioner Services under the laws of India.  
              6.1.3 You warrant that you are qualified and licensed to provide medical services in India and have not committed any act that may affect the continuance or renewal of your license.  
              6.2 Registration and Account Responsibilities  
              6.2.1 To access the Practitioner Services, you must create a Practitioner AccountIcon, provide true, accurate, and complete information, and verify your email and mobile number.  
              6.2.2 You are responsible for maintaining the confidentiality of your credentials and any activity conducted through your account.  
              6.2.3 VHPL reserves the right to verify your identity, qualifications, and credentials. Failure to cooperate may result in suspension or termination of your account.  
              6.2.4 You agree not to share, transfer, assign, or sublicense your Practitioner Account or rights to any third party.  
              6.2.5 VHPL reserves the right to suspend or terminate any Practitioner Account without assigning reasons, at its sole discretion.  
              6.3 Workforce Usage and Supervision  
              6.3.1 If you permit your employees, interns, agents, or other members of your workforce (“Workforce”) to access the Platform or System:  
              (a) You will train them on compliance with these Terms;  
              (b) You remain fully responsible for their actions;  
              (c) You shall take appropriate disciplinary action for any breach.  
              6.3.2 You shall indemnify VHPL against losses or liabilities caused by illegal or unauthorized activities conducted via your Practitioner Account.  
              6.4 Compliance and Representations  
              6.4.1 You undertake to:  
              (a) Notify VHPL of any cases or complaints (past or pending) involving medical negligence or misconduct;  
              (b) Use the Platform and Services strictly in accordance with applicable laws and regulations;  
              (c) Cooperate with VHPL in platform administration and performance evaluations.  
              6.4.2 You shall not access the Services by any means other than those provided by VHPL.  
              6.4.3 If VHPL cannot verify your credentials, it reserves the right to restrict or revoke access.  
              6.5 Consent to Information Use  
              6.5.1 You authorize VHPL to use and disclose your Practitioner Account information for identity verification and professional credential checks.  
              6.5.2 VHPL may disclose this information to third parties and shall not be liable for any consequences arising from such disclosure.  
              6.6 Platform Rights and Restrictions  
              6.6.1 VHPL may at any time suspend or revoke your access to the Platform or Services for any reason, including complaint investigation or internal policy.  
              6.6.2 VHPL may add, remove, or modify the Services or Platform features at its sole discretion.  
              6.6.3 You acquire no ownership rights in the Platform or the Practitioner Account.  
              6.7 Data Security and Breach Notification  
              6.7.1 You agree to maintain adequate administrative, physical, and technical safeguards to protect User Information and System data.  
              6.7.2 You must immediately notify VHPL of any breach or suspected breach of the Platform’s security and follow all mitigation instructions.  
              6.8 Relationship with Users  
              6.8.1 You understand and agree that VHPL only facilitates appointment bookings and does not interfere in medical decision-making.  
              6.8.2 You are solely responsible for professional services rendered to Users and shall be liable for any direct or indirect claims arising from such services.  
              6.8.3 All your interactions with Users shall be independent and governed by applicable laws.  
              6.8.4 You shall refrain from abusive or unprofessional behavior while interacting with Users.  
              6.9 Content and IP Compliance  
              6.9.1 You warrant that all material provided by you (including any content, documents, or listings) does not violate third-party rights or applicable laws.  
              6.9.2 You shall not:  
              (a) Impersonate any other person or entity;  
              (b) Misrepresent your relationship with VHPL;  
              (c) Use the Platform for unlawful purposes;  
              (d) Engage in disruptive or unauthorized activities on the Platform or System.  
              6.10. Practitioners acknowledge that they are solely responsible for ensuring compliance with all applicable medical, ethical, and professional standards, including maintaining valid registrations and insurance.  
              6.10.1 All Practitioners are required to maintain valid professional indemnity insurance covering telemedicine and digital health services. Proof of insurance must be provided to VHPL when asked for.

              **7. DOCTOR REGISTRATION AND PROFILE MANAGEMENT**  
              7.1 Registration Process  
              Practitioners must complete the registration process and create a verified professional profile by providing accurate and up-to-date information, including but not limited to:  
              • Full Name  
              • Contact Details  
              • National Medical Commission (NMC) Registration Number  
              • Academic Qualifications and Degrees  
              • Specialization(s)  
              • Years of Practice  
              7.2 Credential Verification  
              Vydhyo may, at its sole discretion, verify the Practitioner’s credentials and licenses using publicly available sources or through regulatory authorities. However, the Practitioner remains solely responsible for the accuracy, authenticity, and legality of the information and documentation submitted.  
              7.3 Additional Documentation  
              Practitioners may upload supporting documents or certifications to enhance their profile. Vydhyo is under no obligation to independently verify such supplementary content.  
              7.4 Misrepresentation  
              Any misrepresentation, falsification, or omission of material facts may result in immediate suspension or termination of the Practitioner’s profile and may attract civil or criminal liability under applicable laws.  
              7.5 Public Visibility of Profile  
              The Practitioner’s profile, including credentials, qualifications, professional experience, awards, publications, and other voluntarily provided information, shall be publicly visible to Users and treated as non-confidential and non-proprietary. The Practitioner may update or remove such information at any time.  
              7.6 Platform Listings  
              Practitioner details such as name, specialization, experience, clinic address, Hospital address, contact information, consultation timings, services offered, and fees will be automatically listed on the Platform upon being added as a Consultant.  
              7.7 Modification and Delisting Rights  
              Vydhyo reserves the right to modify, delist, or reclassify Practitioner listings and displayed information at its sole discretion. Practitioners may request edits, disable appointment requests, or delist their profiles via their dashboard or by contacting Vydhyo directly.

              **8. FEES, PAYMENTS, AND SETTLEMENT TERMS**  
              8.1 Payment Collection and Settlement  
              Vydhyo shall collect payments on behalf of the Practitioner for all chargeable Appointment(s) booking(s) for consultation(s) or services booked through the Platform. Settlements will be made to the Practitioner’s registered bank account on a C+2 basis (Consultation Day + 2 Working Days), subject to applicable deductions.  
              8.2 Convenience Fee  
              A nominal convenience fee of ₹10 per consultation shall be deducted by Vydhyo before settling the remaining amount to the doctor. In case of physiotherapists, nursing and other healthcare professionals it is according to the agreement between the two parties.  
              8.3 Commission Structure  
              Vydhyo shall charge a commission on most User Services. The applicable rates shall be displayed under the Practitioner’s “Online Service Settings” or communicated separately. Practitioners not agreeing to the structure must refrain from offering such services.  
              8.4 Changes to Commission  
              Vydhyo may introduce new services or revise existing commission rates with or without prior notice. Revised rates shall be deemed accepted upon publication on the Platform or through electronic communication.  
              8.5 Corporate Discounts  
              Corporate tie-ups may involve offering discounts (up to 10%) on consultation fees. Such discounts shall be applied before computing the commission, which will then be charged on the reduced amount.  
              8.6 User Discounts  
              Vydhyo may introduce promotional User Discounts. During such periods, its commission shall be proportionately reduced to offset the discounted amount.  
              8.7 Statement of Earnings  
              The net payable amount will be transferred along with a detailed earnings statement, which shall include:  
              1. Date of consultation  
              2. Type of service  
              3. User details  
              4. Gross fees  
              5. Applicable commission  
              6. Discounts  
              7. Taxes and TDS  
              8. Net amount payable  
              8.8 Payment Delays and Withholding  
              Payments may be delayed or withheld due to:  
              1. Incorrect/incomplete bank details;  
              2. Technical or banking delays;  
              3. Compliance-related restrictions;  
              4. Suspected fraud or breach of this Agreement.  
              8.9 Tax and Regulatory Compliance  
              Practitioners are solely responsible for their own tax filings, PAN information, and statutory compliance. Vydhyo shall not be liable for errors or omissions in the Practitioner’s details or filings.  
              8.10 Indemnification  
              Practitioners shall be solely liable for compliance with applicable laws and taxes on income earned via the Platform. Vydhyo disclaims any liability for the Practitioner’s non-compliance.  
              8.11 Withholding Rights  
              Vydhyo may withhold or cancel payments in case of:  
              1. Service non-fulfilment;  
              2. User complaints;  
              3. Fraud;  
              4. Breach of agreement;  
              5. Regulatory investigation.  
              8.12 Changes to Fee Structures  
              Vydhyo reserves the right to change, discontinue, or revise its services, pricing, and settlement policies. VHPL’s decisions, based on internal records or logs, shall be final unless a verifiable error is proven.

              **9. DOCTOR DISCOVERY, LISTING, AND APPOINTMENT MANAGEMENT**  
              9.1 Algorithmic Listing  
              Vydhyo uses a proprietary, automated algorithm to list Practitioner profiles when Users search for medical services on the Platform. The listing is dynamic and influenced by various factors, including but not limited to:  
              1. User ratings and feedback;  
              2. Consultation volume and frequency;  
              3. Practitioner responsiveness and availability;  
              4. Participation in premium or promotional programs;  
              5. Appointment adherence and patient satisfaction history.  
              9.2 Disclaimer of Rankings  
              Listing order does not represent any fixed ranking, endorsement, or recommendation by Vydhyo. The algorithm is confidential and subject to change without prior notice. Vydhyo disclaims liability for changes in listing position and their consequences.  
              9.3 Premium Listings  
              Premium Listings are promotional placements offered on a bidding basis, subject to availability. Details regarding pricing, eligibility, and duration shall be communicated separately and shall be deemed incorporated into this Agreement.  
              9.4 Profile Publication  
              Practitioners may be listed either through their Practitioner Account or via basic information provided directly to Vydhyo (e.g., name, contact details, consultation timings, etc.). A confirmation will be sent upon listing. Practitioners must notify Vydhyo if they wish to opt out.  
              9.5 Appointment Scheduling Tools  
              The Platform provides scheduling tools including real-time calendar integration and automated reminders. Enabling Instant Booking implies consent to receive and manage appointments through the Platform. Continuity of these tools is subject to timely appointment fulfillment and Vydhyo’s discretion.  
              9.6 Appointment Adherence  
              Practitioners shall honour all confirmed appointments and attend to patients within one (1) hour of the scheduled time. Repeated cancellations, no-shows, delays, or complaints may result in penalties, including reduced visibility or suspension.  
              9.7 Patient Disputes  
              Vydhyo shall not be responsible for patient cancellations, no-shows, or complaints regarding consultation quality. Such matters are to be resolved directly between the Practitioner and the User.  
              9.8 Public Profile Visibility  
              By registering on the Platform, Practitioners acknowledge and consent that their profile, including name, qualifications, and experience, will be publicly visible to Users and may be indexed by search engines.

              **10. CANCELLATION, RESCHEDULING, AND NO-SHOW POLICY**  
              10.1 Practitioner Cancellations  
              Practitioners may cancel or reschedule an appointment by providing at least four (4) hours’ advance notice to the User via the in-app messaging feature.  
              10.2 Patient Cancellations  
              Users are permitted to cancel or reschedule appointments up to four (4) hours in advance. In such cases, no payment shall be remitted to the Practitioner.  
              10.3 No-Show Policy  
              In the event of a User no-show, no consultation fee shall be payable to the practitioner.

              **11. PATIENT FEEDBACK AND RATING SYSTEM**  
              11.1 Feedback Collection  
              Vydhyo facilitates post-consultation feedback from Users via SMS, email, or app notifications. Practitioners are encouraged to inform Users that such feedback requests may follow each consultation.  
              11.2 Data Integrity  
              Feedback is collected in a transparent, time-stamped, and unalterable manner. Feedback may be published on the Platform and will be visible to other Users.  
              11.3 Moderation Policy  
              Vydhyo does not alter or edit User feedback, except in cases involving abusive language, impersonation, spam, or content violating applicable laws or policies. Moderation shall be at Vydhyo’s sole discretion.  
              11.4 Listing Influence  
              User feedback, ratings, and consultation history may influence the Practitioner’s listing position. However, Vydhyo makes no representation or guarantee as to ranking, visibility, or resulting business outcomes.  
              11.5 Disclaimer of Liability  
              Vydhyo shall not be liable for any User-generated content, including comments or ratings. Practitioners acknowledge that such feedback is subjective and does not reflect Vydhyo’s opinion.  
              11.6 Discretion to Modify Feature  
              The feedback feature is provided at Vydhyo’s discretion and may be modified, suspended, or discontinued at any time without notice.  
              11.7. Practitioners may escalate complaints regarding service quality, feedback, or ratings through the Platform’s ‘Report an Issue’ feature or by emailing [support@vydhyo.com]. VHPL will investigate and respond within 10 working days. Practitioners may request review of feedback they believe to be false, abusive, or in violation of Platform policy.

              **12. SYSTEM REQUIREMENTS**  
              12.1 Implementation Responsibility  
              Practitioners shall procure, install, configure, and maintain all hardware, software, internet connectivity, and telecommunications necessary for accessing the Platform. Implementation must conform to Vydhyo’s technical specifications. Failure to comply may result in temporary suspension of access.  
              12.2 Technical Support  
              Upon request and subject to feasibility, Vydhyo may provide technical assistance, which may be chargeable based on prevailing rates and expenses incurred.  
              12.3 Software Updates  
              Practitioners are responsible for maintaining the latest version of the Platform's mobile application. Failure to update the App may restrict access to new features or secure functionalities.  
              12.4 Technical Data Collection  
              By using the Platform, you consent to Vydhyo collecting device-related technical data (e.g., software, hardware, peripherals) for diagnostic, improvement, and optimization purposes.  
              12.5 Location Data  
              If you access location-based services, you explicitly consent to Vydhyo collecting and processing your location data and search history for delivering geo-targeted features and services.  
              12.6. Data Backup Responsibility  
              Practitioners are solely responsible for maintaining independent backups of all data entered or stored on the Platform. VHPL will not be liable for data loss except where caused solely by gross negligence of VHPL’s systems.

              **13. AVAILABILITY MANAGEMENT**  
              13.1. Practitioners shall be responsible for maintaining and updating their availability calendar on the Platform for a rolling period of at least five (5) days at all times.  
              13.2. Failure to update availability or habitual cancellation of appointments may, at the sole discretion of Vydhyo Health Care Private Limited (“VHPL”), result in:  
              1. Reduced visibility in search results;  
              2. Temporary or permanent suspension of the listing;  
              3. Imposition of financial penalties or delisting from the Platform.

              **14. INTELLECTUAL PROPERTY, COPYRIGHT AND USAGE RESTRICTIONS**  
              14.1. Ownership  
              The Platform, including but not limited to its content, layout, features, functionality, source code, databases, interfaces, and any associated Intellectual Property Rights (IPR), is the sole and exclusive property of VHPL. Any present or future modifications, updates, or enhancements shall also belong exclusively to VHPL.  
              14.2. Copyright Protection  
              All content available on the Platform—including text, illustrations, graphics, logos, trademarks, software, video/audio clips, and any content generated by Users or Practitioners—is protected by applicable intellectual property laws. Unauthorized use, duplication, publication, transmission, commercial exploitation, or derivative creation shall be considered an infringement and may attract civil and/or criminal penalties.  
              14.3. Limited License  
              Subject to this Agreement, Practitioners are granted a limited, non-transferable, revocable, and non-exclusive right to access and use the Platform’s dashboard and services solely for the purpose of offering professional healthcare services via the Platform. This license does not permit reverse engineering, resale, commercial replication, sublicensing, or any unauthorized use without prior written consent from VHPL.  
              14.4. License to VHPL for Content Use  
              All Practitioner and User Information, including contributions for responses to questions (whether free or paid), once submitted to VHPL, shall be deemed licensed to VHPL for:  
              1. Display on the Platform;  
              2. Communication of updates and promotional content;  
              3. Statistical aggregation and analysis;  
              4. Enhancement of product features and internal reporting;  
              5. Generation of de-identified, anonymized insights for commercial use.  
              14.5. Reservation of Rights  
              Nothing in this Agreement shall be construed as transferring any right, title, or interest in VHPL’s intellectual property to any Practitioner or third party.

              **15. CLINIC ERP AND TECHNOLOGY SOLUTIONS**  
              15.1. VHPL may provide free-of-cost ERP (Enterprise Resource Planning) software for managing clinic operations including scheduling, billing, and patient data.  
              15.2. The Practitioner shall retain ownership of all patient-related data entered in the ERP system and shall be solely responsible for ensuring compliance with data protection and privacy regulations.  
              15.3. While VHPL implements industry-standard safeguards, it shall not be held liable for data breaches, loss, or corruption caused by technical failure, hacking, or force majeure.  
              15.4. Technical issues such as bugs, lags, or system errors shall be resolved on a best-effort basis, without any guaranteed service levels or uptime commitments.

              **16. THIRD-PARTY FINANCIAL SERVICES**  
              16.1. The Platform may facilitate optional integrations with third-party financial service providers, including NBFCs, banks, or aggregators, to offer loan/EMI options to Users.  
              16.2. Any arrangement or agreement between the User and a third-party financial institution shall be entirely independent, and VHPL or the Practitioner shall not be responsible or liable for any such transactions or resulting obligations.

              **17. RIGHTS AND OBLIGATIONS RELATING TO CONTENT**  
              17.1. In accordance with Rule 3(2) of the Information Technology (Intermediaries Guidelines) Rules, 2011, the Practitioner shall not upload, host, display, modify, publish, transmit, or share any content or information through the Platform that:  
              (a) belongs to another individual or entity without proper authorization;  
              (b) is defamatory, obscene, pornographic, invasive of privacy, hateful, or otherwise unlawful;  
              (c) exploits, harms, or targets minors;  
              (d) infringes intellectual property or proprietary rights;  
              (e) violates any applicable laws or regulations;  
              (f) misleads or deceives recipients;  
              (g) impersonates another individual or entity;  
              (h) contains malware, viruses, or malicious code;  
              (i) poses a threat to India’s sovereignty, public order, or friendly relations with foreign states.  
              17.2. VHPL reserves the right, at its sole discretion, to take one or more of the following actions if a Practitioner violates the above:  
              (a) remove or disable access to the offending content;  
              (b) suspend or terminate the Practitioner’s access to the Platform or Services;  
              (c) initiate legal or regulatory action in accordance with applicable laws.

              **18. USE AND DISCLOSURE OF USER INFORMATION**  
              18.1. The Practitioner shall at all times comply with applicable laws relating to the collection, access, use, processing, storage, transmission, and disclosure of User Information, including sensitive personal data, as defined under the Information Technology Act, 2000 and related rules.  
              18.2. The Practitioner shall ensure that all individuals or entities acting on their behalf, including but not limited to employees, agents, interns, affiliates, or representatives, adhere to applicable data privacy and protection laws.  
              18.3. The Practitioner shall not use, disclose, or process any User’s personal or sensitive personal data for purposes other than providing the intended medical services, unless prior written informed consent has been obtained from the User in accordance with applicable law.  
              18.4. It shall be the sole responsibility of the Practitioner to obtain and retain any legally required consent or authorization from Users for the collection, use, disclosure, or transmission of their personal data. VHPL shall not be held liable for the Practitioner’s failure to do so or for any misuse of such data.  
              18.5. VHPL reserves the right to remove content, restrict access, or revoke registration in the event of any misuse or unauthorized handling of User Information by the Practitioner.  
              18.6. Practitioners must obtain explicit, written or digital consent from each User prior to collecting, using, or disclosing any personal or sensitive personal data. This consent must be retained for a minimum of three years and be made available to VHPL or regulatory authorities upon request. Users must be informed of their right to withdraw consent at any time, and such withdrawal shall be promptly honored.

              **19. PROFESSIONAL RESPONSIBILITY AND LIABILITY**  
              19.1. All medical decisions, diagnoses, prescriptions, and consultations are rendered independently by the Practitioner, and VHPL shall bear no responsibility for such professional conduct.  
              19.2. VHPL functions solely as a technology facilitator and disclaims any liability for malpractice, errors, or negligence arising from the Practitioner’s medical services.  
              19.3. The Practitioner agrees to indemnify, defend, and hold harmless VHPL from any legal actions, claims, or damages arising due to their professional acts or omissions.

              **20. FOLLOW-UP CONSULTATIONS**  
              20.1. Follow-up appointments may be scheduled via the Platform by the Practitioner at least forty-eight (48) hours prior to the desired date.  
              20.2. While VHPL will send automated reminders, it shall not be liable for missed notifications due to technical delays or oversight.

              **21. PRIORITY OF ONLINE BOOKINGS OVER WALK-INS**  
              21.1. The Practitioner shall prioritize Users with pre-scheduled appointments on the Platform over walk-in patients.  
              21.2. Walk-ins should not cause delays exceeding thirty (30) minutes for online-booked Users. Any violation may attract penalties or negative feedback, or complaints.

              **22. COMMUNICATION TO THE PRACTITIONER**  
              22.1. By registering and using the Platform, the Practitioner consents to receive communications from VHPL via various modes, including SMS, email, calls, WhatsApp messages, in-app notifications, or other channels.  
              22.2. Such communications may relate to registrations, appointments, updates, marketing, offers, surveys, newsletters, policy changes, and service-related information.  
              22.3. These communications are considered transactional and necessary for use of the Platform. VHPL shall not be responsible for any non-receipt caused by technical issues or third-party failures. Practitioners must independently track their appointments.  
              22.4. All communications shall be deemed delivered upon dispatch, regardless of acknowledgment or access. Withdrawal of consent to such communications requires the Practitioner to discontinue their account.

              **23. TECHNOLOGY SERVICES OFFERED TO PRACTITIONERS**  
              Practitioners shall have access to the following technology tools and features via the Platform:  
              1. Online appointment booking and patient discovery tools;  
              2. Clinic workflow ERP;  
              3. CRM for patient communication;  
              4. Real-time availability scheduling;  
              5. EMI/loan integration for patients;  
              6. POS and QR-code systems;  
              7. Business analytics dashboard;  
              8. Optional premium listings and promotions.

              **24. CAUTION REGARDING USE OF SERVICES**  
              24.1. The Platform is not intended for emergency use. Practitioners must not use it for urgent care or critical interventions requiring immediate medical attention.  
              24.2. VHPL disclaims all liability for any adverse outcomes arising from use of the Services during emergencies. Practitioners are expected to guide patients to appropriate emergency medical services.

              **25. DISCLAIMER OF WARRANTIES, GUARANTEES, AND REPRESENTATIONS**  
              25.1. The Platform and Practitioner Services are provided on an “as is” and “as available” basis. Use is at the sole risk and responsibility of the Practitioner.  
              25.2. VHPL makes no warranties—express or implied—regarding the accuracy, timeliness, reliability, or utility of any Platform content or services.  
              25.3. VHPL disclaims all liability for errors, omissions, or third-party misconduct and does not guarantee the identity, credentials, or intent of any User, patient, or other Practitioner.  
              25.4. VHPL may revise or discontinue the Platform or Services at its sole discretion, without prior notice. Continued use constitutes acceptance of such modifications.  
              25.5. Access and usage rights are personal, limited, non-transferable, and revocable at VHPL’s discretion.  
              25.6. VHPL does not warrant that:  
              1. The Platform will function uninterrupted or be free of errors or security breaches;  
              2. Any defects will be corrected;  
              3. Content will meet your expectations or intended use;  
              4. Results obtained will be accurate, timely, or useful.  
              25.7. VHPL is not liable for any damage caused to Practitioner’s hardware, software, or data resulting from Platform access.  
              25.8. To the fullest extent permitted by applicable law, all implied warranties, including merchantability or fitness for a particular purpose, are expressly disclaimed by VHPL.

              **26. INFORMATION UPLOADED BY THE PRACTITIONER**  
              26.1. While Vydhyo adopts reasonable technical and organizational measures to safeguard the data transmitted or stored on its servers, the Practitioner acknowledges and agrees that any patient data, medical records, or health-related information voluntarily uploaded, disclosed, or shared on the Platform is done so at the Practitioner’s sole risk and discretion. By uploading such information, the Practitioner consents to the storage and processing of such data by Vydhyo in accordance with applicable laws and the Company’s Privacy Policy.  
              26.2. Certain information submitted by the Practitioner may qualify as "Sensitive Personal Data or Information" under the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011. The Practitioner acknowledges that the collection, use, processing, and disclosure of such data by VHPL shall be governed by its Privacy Policy, which forms an integral part of these Terms.

              **27. LIMITATION OF LIABILITY**  
              27.1. Under no circumstances shall Vydhyo Health Care Private Limited (VHPL), including its directors, officers, employees, agents, affiliates, or licensors, be liable for any direct, indirect, incidental, consequential, punitive, exemplary, or special damages arising from or related to the Practitioner’s use of the Platform or Services, whether based in contract, tort (including negligence), strict liability, or otherwise.  
              27.2. Without limiting the generality of the foregoing, VHPL shall not be liable for:  
              1. Interruptions, delays, or errors in Platform functionality;  
              2. Damage or loss resulting from reliance on Platform content;  
              3. Technical failures, third-party disruptions, or force majeure events;  
              4. Data loss due to hardware/software failure at the Practitioner or server level;  
              5. User comments, reviews, or feedback, including any reputational harm;  
              6. Any actions or omissions of Users, other Practitioners, or patients.  
              27.3. VHPL does not guarantee that the Platform or Services will be uninterrupted, error-free, or free from viruses or other harmful components. The Platform and Services are provided strictly on an “as is” and “as available” basis, without any warranties, express or implied.  
              27.4. In no event shall VHPL’s total aggregate liability for any and all claims exceed the total subscription fees or commissions received by VHPL from the Practitioner for the use of the Platform in the six (6) months preceding the claim.  
              27.5. VHPL shall further not be liable for:  
              1. Errors in bank details submitted by the Practitioner;  
              2. Unauthorized access to Practitioner data or communications;  
              3. Missed notifications or reminders due to system limitations;  
              4. Breaches or violations of data protection laws by the Practitioner;  
              5. Any claims arising from the Practitioner’s negligence or professional misconduct.  
              27.6. VHPL shall not be responsible for maintaining, recovering, or reproducing Practitioner data. The Practitioner is solely responsible for maintaining appropriate data backups.  
              27.7. The Practitioner hereby releases VHPL and its officers, agents, and employees from any claims relating to lost profits, data loss, business disruption, or reputational damage.  
              27.8. It is the Practitioner’s sole responsibility to ensure compliance with all applicable legal, ethical, and professional obligations related to patient care, data handling, and use of the Platform.  
              27.9. Upon termination of a Practitioner AccountIcon, VHPL will retain Practitioner and User data only as required by applicable law or regulatory guidelines, and for no longer than 1 year. Practitioners may request deletion of their data by contacting VHPL, subject to legal retention requirements. VHPL will confirm deletion or anonymization within 30 days of the request.

              **28. VIOLATIONS OF SYSTEM OR NETWORK SECURITY**  
              28.1. The Practitioner shall access and use the Platform in a lawful, ethical, and professional manner and shall cooperate with Vydhyo in maintaining the security and integrity of the Platform and Services.  
              28.2. Any actual or attempted breach of system, application, or network security is strictly prohibited and may result in immediate suspension or termination of the Practitioner AccountIcon, civil liability, and/or criminal prosecution. Prohibited activities include, but are not limited to:  
              28.2.1. Uploading viruses, trojans, malware, or harmful code;  
              28.2.2. Unauthorized access, scanning, or probing of systems or data;  
              28.2.3. Monitoring or intercepting Platform traffic without consent;  
              28.2.4. Disrupting Platform operations through denial-of-service attacks or other methods;  
              28.2.5. Uploading or disseminating unlawful, offensive, or defamatory content;  
              28.2.6. Reverse-engineering or tampering with the Platform;  
              28.2.7. Unauthorized linking, scraping, or framing of Platform content;  
              28.2.8. Transmitting unsolicited messages or spam to Users or Practitioners;  
              28.2.9. Posting misleading, defamatory, or competitive material.  
              28.3. The Practitioner shall not deploy any tools, devices, or techniques that disrupt or interfere with normal Platform operation or affect transactions or usage by other Users.  
              28.4. VHPL reserves the right to pursue all available legal and equitable remedies, including injunctive relief, civil claims, and reporting to law enforcement authorities, in response to any breach or attempted breach of system or network security. VHPL also reserves the right to recover compensatory and punitive damages for any resulting harm.

              **29. FORCE MAJEURE**  
              29.1. Neither VHPL nor the Practitioner shall be held liable for any failure or delay in the performance of their respective obligations under these Terms if such failure or delay is caused by events beyond their reasonable control, including but not limited to acts of God, natural disasters, war, civil unrest, terrorism, epidemics, pandemics, governmental actions, labour strikes, power outages, internet failures, server crashes, or other unforeseen and unavoidable circumstances (“Force Majeure Event”).  
              29.2. The affected party shall provide prompt written notice to the other party upon the occurrence of a Force Majeure Event and shall use reasonable efforts to resume performance as soon as practicable after the cessation of the Force Majeure Event.

              **30. INDEMNIFICATION**  
              30.1. The Practitioner agrees to indemnify, defend, and hold harmless Vydhyo Health Care Private Limited (“VHPL”), its directors, officers, employees, agents, affiliates, contractors, licensors, and subsidiaries (collectively, the “Indemnified Parties”) from and against any and all claims, liabilities, damages, losses, expenses, and costs (including reasonable attorneys' fees) arising out of or in connection with:  
              (a) any breach of these Terms or applicable law by the Practitioner;  
              (b) the Practitioner’s professional conduct, negligence, error, or omission;  
              (c) any misrepresentation or false information provided by the Practitioner;  
              (d) misuse of the Platform or any Patient Information;  
              (e) the conduct of any individual accessing the Platform through the Practitioner’s credentials.  
              30.2. Without prejudice to the generality of the above, the Practitioner specifically agrees to indemnify VHPL against any liability arising out of:  
              (a) incorrect diagnosis, treatment, prescription, or medical advice;  
              (b) medical malpractice or professional negligence;  
              (c) inappropriate behaviour by the Practitioner or their staff;  
              (d) appointment cancellations, service delays, or fee disputes;  
              (e) adverse health outcomes suffered by any User arising from consultations.  
              30.3. The Practitioner shall also indemnify VHPL from claims, losses, or damages resulting from fraudulent or defamatory content, including manipulation of the rating/review system by the Practitioner or their associates.  
              30.4. The obligations under this clause shall survive the termination or expiration of this Agreement.

              **31. TERM, TERMINATION AND DISPUTES**  
              31.1. These Terms shall remain effective for so long as the Practitioner continues to access or use the Platform or any associated Services. The Practitioner may request termination by providing thirty (30) days’ prior written notice through the “Contact Us” form on the Platform. VHPL may require continued subscription until all pending appointments, services, or dues are resolved.  
              31.2. VHPL reserves the right to suspend or terminate the Practitioner’s account and access to the Platform without notice in the event of:  
              (a) breach of these Terms, the Privacy Policy, or any applicable law;  
              (b) failure to verify or authenticate submitted information;  
              (c) any conduct that may result in legal liability for VHPL or its Users, or that adversely affects VHPL’s business interests.  
              31.3. Upon termination, the Practitioner shall cease all access to the Platform. VHPL shall not be responsible for retaining or restoring any data, messages, or records. The Practitioner shall remain solely responsible for backup and storage in accordance with legal and professional obligations.  
              31.4. VHPL may take legal, technical, or other actions deemed necessary, including deletion of content and permanent revocation of access, in the event of non-compliance with these Terms.  
              31.5. Clauses relating to Professional Responsibility, Confidentiality, Indemnity, Limitation of Liability, Intellectual Property, Dispute Resolution, and all other provisions which by their nature survive termination shall remain in force after termination.

              **32. APPLICABLE LAW AND DISPUTE RESOLUTION**  
              32.1. These Terms and any disputes arising in connection with them shall be governed exclusively by the laws of India, without regard to its conflict of laws principles.  
              32.2. The courts at Hyderabad, Telangana State, shall have exclusive jurisdiction over any dispute arising under these Terms, including disputes related to use of the Platform or Services.  
              32.3. Any dispute, controversy, or claim arising out of or in connection with this Agreement, including the interpretation or enforceability of the arbitration clause, shall be resolved by final and binding arbitration.  
              32.4. Any dispute shall be referred to a sole arbitrator mutually appointed by both parties. If the parties cannot agree within 30 days, the arbitrator shall be appointed in accordance with the Arbitration and Conciliation Act, 1996.  
              32.5. The seat and venue of arbitration shall be Hyderabad, Telangana State, and the proceedings shall be conducted in English.  
              32.6. The arbitral award shall be final, conclusive, and binding upon the parties and enforceable under applicable law.

              **33. ASSIGNMENT**  
              33.1. VHPL may assign, transfer, or delegate this Agreement and its rights and obligations hereunder, in whole or in part, to any of its affiliates, group companies, successors, or as part of a merger, acquisition, or corporate restructuring, without requiring the Practitioner’s prior consent.  
              33.2. The Practitioner shall not assign, transfer, sublicense, or otherwise convey any of their rights or obligations under these Terms to any third party. Any such attempted assignment shall be void ab initio.

              **34. MODIFICATION AND TERMINATION**  
              34.1. VHPL reserves the right, at its sole discretion, to modify, revise, amend, suspend, or terminate these Terms or the Practitioner Services, in whole or in part, at any time and without prior notice.  
              34.2. Any changes to the Terms shall be communicated through email notifications or Platform alerts. Continued use of the Platform or Services after such communication shall constitute the Practitioner’s acceptance of the modified Terms.  
              34.3. VHPL will notify Practitioners of any material changes to the Privacy Policy or security practices via email and Platform notifications at least 15 days prior to implementation. Continued use of the Platform after such notice constitutes acceptance of the changes.

              **35. THEFT OR UNAUTHORIZED USE OF PRACTITIONER SERVICES**  
              35.1. The Practitioner agrees to promptly notify VHPL in writing via the “Contact Us” form on the Website upon discovering or suspecting any theft, unauthorized access, misuse, or fraudulent activity involving their Practitioner Account or Services. Such notification shall include relevant account details and a full description of the suspected activity.  
              35.2. Failure to report such activity within a reasonable period may result in the suspension or termination of Services, and the Practitioner may be held liable for any charges or losses incurred due to such unauthorized use.  
              35.3. The Practitioner shall remain solely responsible for all activity conducted through their Practitioner AccountIcon, including any misuse resulting from modem hijacking, network breaches, unauthorized disclosures, or intentional or negligent access granted to third parties.  
              35.4. VHPL shall not be obligated to provide refunds, extend subscription terms, or waive fees resulting from unauthorized use, unless such use is directly attributable to a verified failure of VHPL’s systems and not the Practitioner’s negligence or misconduct.

              **36. MISUSE OF PRACTITIONER SERVICES**  
              36.1. VHPL reserves the right to restrict, suspend, or permanently terminate a Practitioner’s access to the Platform or Services in the event of any misuse.  
              36.2. Misuse includes, but is not limited to:  
              1. creating multiple or fraudulent Practitioner profiles;  
              2. using false, misleading, or infringing content;  
              3. impersonating another person or entity;  
              4. attempting to manipulate ratings or reviews;  
              5. any behaviour deemed unethical, abusive, or in violation of these Terms or applicable law.  
              36.3. VHPL may implement a “three-strike” policy or, where warranted, proceed with immediate termination without prior notice, based on the severity or recurrence of violations.

              **37. SEVERABILITY**  
              37.1. If any provision of these Terms is found to be invalid, unlawful, or unenforceable by a competent court or authority, such provision shall be deemed severed from the Agreement. The remainder of the Agreement shall continue to be valid and enforceable to the fullest extent permitted by law.

              **38. WAIVER**  
              38.1. No delay or failure by VHPL in exercising any right, remedy, or power under these Terms shall operate as a waiver thereof. Any waiver granted shall be in writing and shall not constitute a waiver of any future rights or remedies, unless expressly stated.

              **39. CONTACT INFORMATION**  
              39.1. For any inquiries, clarifications, concerns, or support relating to these Terms or the Practitioner Services, you may contact VHPL through the “Contact Us” form available on the Platform.  
              39.2. For any concerns regarding data privacy, security, or grievances, Practitioners and Users may contact the designated Grievance Officer/Data Protection Officer at:  
              Email: vydhyo@gmail.com  
              Ph no. 9666955501  
              All grievances will be acknowledged within 48 hours and resolved within one month, in accordance with applicable law.

              **ACKNOWLEDGEMENT AND ACCEPTANCE**  
              BY CLICKING ON THE “I AGREE” BUTTON, ACCESSING YOUR ACCOUNT, OR CONTINUING TO USE THE PLATFORM OR PRACTITIONER SERVICES, YOU, THE PRACTITIONER, EXPRESSLY ACKNOWLEDGE THAT YOU HAVE READ, UNDERSTOOD, AND AGREED TO BE BOUND BY THESE TERMS AND CONDITIONS. THIS ACTION CONSTITUTES A LEGALLY BINDING AGREEMENT UNDER APPLICABLE LAW BETWEEN YOU AND VYDHYO HEALTH CARE PRIVATE LIMITED.  
              PLEASE REVIEW THESE TERMS PERIODICALLY. IN THE EVENT OF A CONFLICT BETWEEN THESE TERMS AND ANY PRIOR VERSIONS OR EXTERNAL COMMUNICATIONS, THE MOST RECENT VERSION PUBLISHED ON THE PLATFORM SHALL PREVAIL.
            </Text>
          </ScrollView>
          <Pressable style={styles.closeButton} onPress={() => setModalVisible(false)}>
            <Text style={styles.closeButtonText}>Close</Text>
          </Pressable>

         <Pressable
  style={styles.closeButton}
  onPress={() => {
    setModalVisible(false);
    setTermsAccepted(true); // ✅ check the box when "Agree" is pressed
  }}
>
  <Text style={styles.closeButtonText}>Agree</Text>
</Pressable>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    width: '90%',
    maxHeight: '80%',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    marginBottom: 15,
    textAlign: 'center',
  },
  modalScroll: {
    maxHeight: '70%',
  },
  modalBody: {
    fontSize: 14,
    lineHeight: 20,
    color: '#333',
  },
  closeButton: {
    marginTop: 15,
    backgroundColor: '#007AFF',
    padding: 10,
    borderRadius: 5,
    alignItems: 'center',
  },
  closeButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
});

export default TermsAndConditionsModal;