export type RootStackParamList = {
  Splash: undefined;
  Authloader:undefined;
  Login: undefined;
  PersonalInfo: undefined;
  Specialization: undefined;
  Practice: undefined;
  ConsultationPreferences: undefined;
  FinancialSetupScreen: undefined;
  KYCDetailsScreen: undefined;
  ConfirmationScreen: undefined;
  ProfileReview: undefined;
  AccountVerified: undefined;
  DoctorDashboard: undefined;
  Sidebar: undefined;
  AddAppointment: undefined;
  Availability: undefined;
  StaffManagement: undefined;
  AddStaff: undefined;
  MyPatient: undefined;
  Appointments: undefined;
  Dashboard: undefined;
  Accounts: undefined;
  Clinic: undefined;
  AddClinic: undefined;
  Reviews: undefined;
  DoctorDetails:undefined;
  PatientDetails:undefined;
  Vitals:undefined;
  DiagnosisMedication:undefined;
  AdviceFollowup:undefined;
  PrescriptionPreview:undefined;
  expenditure:undefined;
  Profile: undefined;
  PreviousPrescription: undefined;
  EPrescriptionList: undefined;
  labs:undefined;
  LabPatientManagement: undefined;
  Billing:undefined;
  Pharmacy:undefined;
  PharmacyPatientsTab:undefined;
  PharmacyMedicinesTab:undefined;
  Templates:undefined;
  FollowUps:undefined;
  PinManagement:undefined;
  PatientReports:undefined;
  ProviderTabDashboard: undefined;
};